services:
  android:
    image: budtmo/docker-android:emulator_14.0
    platform: linux/amd64
    container_name: android-test
    privileged: true

    devices:
      - /dev/kvm:/dev/kvm

    ports:
      - "6080:6080"
      - "5555:5555"

    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"

    volumes:
      - ./apk:/apk